spring.application.name=Blog-Application

spring.datasource.url=jdbc:postgresql://localhost:5432/BlogApplication
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#spring.security.user=ankit
#spring.security.password=ankit
#spring.security.user.roles=ADMIN

app.jwt-secret=codewithkansalbyAnkitKansalASoftwareDeveloperfromIndia
app.jwt-expiration-milliseconds=604800000
